In [6]:
task = [set((0, 1)), set((0, 1, 2, 3)), set((0, 1, 2, 3, 4, 5))]

set.union(*[i for i in task])

{0, 1, 2, 3, 4, 5}

In [5]:
for i in task:
    print(i)

(0, 1)
(0, 1, 2, 3)
(0, 1, 2, 3, 4, 5)


workflow:

5 tasks (index 0-4)
- train on task 0. use full task 0 dataset.
- train on task 1. select p percent of task 0 dataset. store where???
- create a loss function to call anywhere. generic loss function.
- 
    - sum of the individual 


questions for tomorrow:
- sample b elements for **each step of training** or just at the beginning. does the memory set stay constant across memory sets
- in _get_task_dataloader, why are we doing `randperm` and `shuffle=True`. Seems redundant.


In [1]:
import numpy as np

In [4]:
hkl_sum = np.array([3, 4, 8, 11, 12])
a = 5.5
lam = 0.3
d = a/np.sqrt(hkl_sum)

In [5]:
d

array([3.17542648, 2.75      , 1.94454365, 1.6583124 , 1.58771324])

In [11]:
theta = np.arcsin(lam/(2*d))*180/np.pi

In [12]:
theta

array([2.70753124, 3.12677611, 4.42412963, 5.18969158, 5.42113232])

In [13]:
theta*2

array([ 5.41506248,  6.25355223,  8.84825926, 10.37938317, 10.84226464])

In [17]:
lam = 1.5406
lam/2/np.sin(44.67/2*np.pi/180) * np.sqrt(2)

2.866599322885289